import {
  API_URL,
  USER_API_URL,
  STORIES_API_URL,
  GOOGLE_WEB_CLIENT_ID,
  GOOGLE_ANDROID_CLIENT_ID,
  CLOUDINARY_UPLOAD_PRESET,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_UPLOAD_URL,
  DEFAULT_IMAGE_URL,
  PUBLICACIONES_API_URL,
  CHAT_SOCKET_URL
} from "@env";

export {
  API_URL,
  USER_API_URL,
  STORIES_API_URL,
  GOOGLE_WEB_CLIENT_ID,
  GOOGLE_ANDROID_CLIENT_ID,
  CLOUDINARY_UPLOAD_PRESET,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_UPLOAD_URL,
  DEFAULT_IMAGE_URL,
  PUBLICACIONES_API_URL,
  CHAT_SOCKET_URL
};