import {
  API_URL,
  USER_API_URL,
  STORIES_API_URL,
  GOOGLE_WEB_CLIENT_ID,
  GOOGLE_ANDROID_CLIENT_ID,
  CLOUDINARY_UPLOAD_PRESET,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_UPLOAD_URL,
  DEFAULT_IMAGE_URL,
  PUBLICACIONES_API_URL,
  CHAT_SOCKET_URL
} from "@env";

export const API_URL = API_URL;
export const USER_API_URL = USER_API_URL;
export const STORIES_API_URL = STORIES_API_URL;
export const GOOGLE_WEB_CLIENT_ID = GOOGLE_WEB_CLIENT_ID;
export const GOOGLE_ANDROID_CLIENT_ID = GOOGLE_ANDROID_CLIENT_ID;
export const CLOUDINARY_UPLOAD_PRESET = CLOUDINARY_UPLOAD_PRESET;
export const CLOUDINARY_CLOUD_NAME = CLOUDINARY_CLOUD_NAME;
export const CLOUDINARY_UPLOAD_URL = CLOUDINARY_UPLOAD_URL;
export const DEFAULT_IMAGE_URL = DEFAULT_IMAGE_URL;
export const PUBLICACIONES_API_URL = PUBLICACIONES_API_URL;
export const CHAT_SOCKET_URL = CHAT_SOCKET_URL;